apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restore2-ingress
  labels:
    app: restore2
    backstage.io/kubernetes-id: restore2 
spec:
  rules:
    - host: api-restore2-anderson-dev.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restore2
                port: 
                  number: 80
  tls:
  - hosts:
    - api-restore2-anderson-dev.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: restore2
  labels:
    app: restore2
    backstage.io/kubernetes-id: restore2
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: restore2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restore2
  labels:
    app: restore2
    backstage.io/kubernetes-id: restore2
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: restore2
  template:
    metadata:
      labels:
        app: restore2
    spec:
      containers:
      - name: restore2
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/restore2:{image-tag}
        ports:
        - containerPort: 5000
